routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/companies','CompaniesController');
Route::resource('projects','ProjectsController');
Route::resource('roles','RolesController');
Route::resource('task','TasksController');
Route::resource('users','UsersController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $fillable =[
        'id',
        'name',
        'description',
        'user_id',
         
    ];
    public function user(){
        return $this->belongsTo('App/User');
    }

    public function projects(){
        return $this->hasMany('App\Project');
    }

}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = Company::all();

        return view('companies.index',['companies'=> $companies]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
     //   $companies = Company::where('id', $company->id);
        $companies = Company::find($company->id);
       
        return view('companies.show',['company'=> $company ]);


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
        $companies = Company::find($company->id);
       
        return view('companies.edit',['company'=> $company ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        //

        $companyUpdate = Company::where('id',$company->id)
        ->update([
            'name'=>$request->input('name'),
            'description'=>$request->input('description')
        ]);

        if($companyUpdate){
            return redirect()->route('companies.show',['company'=>$company->id])
            ->with('sucess','company updated');
        }
          
       return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        //
    }
}

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')




  <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 15px;">

    <form method="post" action="{{ route('companies.update',[$company->id])}}">
             {{ csrf_field() }}
      <input type="hidden" name="_method" value="put">
      <div class="form-group">
        <label for="company-name">Name<span class="required">*</span></label>
        <input class="form-control" id="company-name" required name="name" spellcheck="false" placeholder="Enter Name" value="{{$company->name}}" />
        
      </div>


      <div class="form-group">
        <label for="company-content">Description</label>
        <textarea placeholder="Enter Description" style="resize: vertical;" id="company-content" name="description" rows="5" spellcheck="false" class="form-control autosize-target text-left"> 
        {{ $company->description}}</textarea>
        
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

  </div>


<div class="col-md-3 col-lg-3 col-sm-3 pull-right">
  <div class="sidebar-module">
    <h4>Action</h4>
    <ol class="list-unstyled">
      <li><a href="/companies/{{ $company->id }}">view Companies</a></li>
      <li><a href="/companies/">All Companies</a></li>
      
    </ol>
  </div>
</div>


@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
 <div class=" col-md-6 col-lg-6">
<div class="panel panel-primary">
<div class="panel-heading">Companies</div>
<div class="panel-body">
   
  <ul class="list-group">
  @foreach($companies as $company)
  <li class="list-group-item" ><a href="/companies/{{$company->id }} "> {{$company->name }} </a></li>
  @endforeach
  </ul>

   

   </div>
</div>
</div>  
@endsection

resources/views/companies/show.blade.php
 @extends('layouts.app')

 @section('content')

    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

     <div class="jumbotron">
          <h1>{{ $company->name }}</h1>
          <p class="lead">{{ $company->description }}</p>
    
      </div>

     <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px;">
        @foreach($company->projects as $project)

           <div class="col-lg-4 col-md-4 col-sm-4">

                  <h2>{{ $project->name }}</h2>
                  <p class="text-danger">{{ $project->description }}</p>
                  <p><a class="btn btn-primary" href="/projects/{{ $project->id}}" role="button">View Project »</a></p>

           </div>

        @endforeach
      </div>
   </div>

    <div class="col-md-3 col-lg-3 col-sm-3 pull-right">
       <div class="sidebar-module">
           <h4>Action</h4> 
           <ol class="list-unstyled">
             <li><a href="/companies/{{ $company->id }}/edit">Edit</a></li>
             <li><a href="#">Delete</a></li>
             <li><a href="#">Add new member</a></li>
           </ol>
       </div>
     </div>


 @endsection